name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<title>index</title>"
          replace: "<title>TSSC IOW</title>"
          regex: false
          include: "**index.html"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
